name: Swift Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    name: Build and Test on Linux
    
    runs-on: ubuntu-latest
    container:
      image: swift:6.1.0
    
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build
